spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true  #This ensures the execution happens after Hibernate creates the tables
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com # Gmail's email server address
    port: 587  # Gmail's secure email port
    username: ${GMAIL_ADDRESS}        # Replace with your Gmail
    password: ${GMAIL_APP_PASSWORD}           # App password (Google's security requirement for apps accessing Gmail)
    properties:
      mail:
        smtp:
          auth: true # "Yes, I want to authenticate"
          starttls:
            enable: true # "Use encryption for security"

  # ===== SPRING CLOUD AWS CONFIG =====
  cloud:
    aws:
      credentials:
        access-key: ${MQTT_AWS_ACCESS_ID}
        secret-key: ${MQTT_AWS_ACCESS_KEY}
      region:
        static: eu-north-1  # Default for SQS, IoT, etc.
        auto: false
      ses:
        region: ${email.ses.region}   # ✅ SES-specific region override for automatic ses bean



# ===== EMAIL CONFIGURATION (Clean and Organized) =====
email:
  provider: ses
  ses:
    region: us-east-1
    from-email: noreply@rehabgait.com

jwt:
  secret: ${JWT_SECRET}
  expiration:
    ms: 432000000

# ===== IoT Core CONFIG (For your direct AWS SDK usage) =====
mqtt:
  client:
    endpoint: ${MQTT_CLIENT_ENDPOINT}
    id: ${MQTT_CLIENT_ID}
  aws:
    accessKey: ${MQTT_AWS_ACCESS_KEY}
    accessId: ${MQTT_AWS_ACCESS_ID}


# ===== S3 CONFIG (For your direct AWS SDK usage) =====
aws:
  region: eu-north-1
  s3:
    bucket: gait-analysis-reports

app:
  sqs:
    queue-name: rehabgait-processing-request-dev2
  cors:
    allowed-origin: http://localhost:5173



microservices:
  data:
    processing:
      url: http://localhost:8000/process-session




# http://localhost:8080/swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG



frontend:
  base:
    url: ${FRONTEND_BASE_URL}
#client:
#  domains:
#        list:
#          - apple
#          - banana


#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate.SQL: DEBUG
#    com:
#      _yp:
#        gaitMate: DEBUG